# Generated by Django 5.2.3 on 2025-06-15 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='master1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('code', models.IntegerField(max_length=6, verbose_name='Code')),
                ('mastertype', models.IntegerField(max_length=6, verbose_name='MasterType')),
            ],
            options={
                'verbose_name': 'Master',
                'verbose_name_plural': 'Masters',
            },
        ),
        migrations.CreateModel(
            name='tran2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_type', models.IntegerField(max_length=6, verbose_name='Voucher Type')),
                ('date', models.DateField(verbose_name='Date')),
                ('vch_no', models.IntegerField(max_length=6, verbose_name='Voucher No')),
                ('quantity', models.FloatField(verbose_name='Quantity')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('mastercode1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockreport.master1', verbose_name='Master Code')),
            ],
        ),
    ]
