# Generated by Django 4.2 on 2025-08-01 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(help_text='SQL Server host or address', max_length=200)),
                ('database', models.CharField(default='your_db', help_text='SQL Server database name', max_length=100)),
                ('username', models.CharField(help_text='SQL Server username', max_length=100)),
                ('password', models.CharField(help_text='SQL Server password', max_length=100)),
                ('port', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only one configuration can be active at a time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API Configuration',
                'verbose_name_plural': 'API Configurations',
            },
        ),
        migrations.CreateModel(
            name='master1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('code', models.IntegerField(verbose_name='Code')),
                ('mastertype', models.IntegerField(verbose_name='MasterType')),
            ],
            options={
                'verbose_name': 'Master',
                'verbose_name_plural': 'Masters',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('device_id', models.CharField(help_text='Unique device identifier', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
            },
        ),
        migrations.CreateModel(
            name='UserAPIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(help_text='SQL Server host or address', max_length=200)),
                ('database', models.CharField(default='your_db', help_text='SQL Server database name', max_length=100)),
                ('username', models.CharField(help_text='SQL Server username', max_length=100)),
                ('password', models.CharField(help_text='SQL Server password', max_length=100)),
                ('port', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is active for the user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User API Configuration',
                'verbose_name_plural': 'User API Configurations',
            },
        ),
        migrations.CreateModel(
            name='tran2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vch_Type', models.IntegerField(verbose_name='Voucher Type')),
                ('RecType', models.IntegerField(default=0, verbose_name='Record Type')),
                ('date', models.DateField(verbose_name='Date')),
                ('vch_no', models.CharField(max_length=50, verbose_name='Voucher No')),
                ('quantity', models.FloatField(verbose_name='Quantity')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('mastercode1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockreport.master1', verbose_name='Master Code')),
            ],
        ),
        migrations.CreateModel(
            name='tran1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vch_Type', models.IntegerField(verbose_name='Voucher Type')),
                ('Date', models.DateField(verbose_name='Date')),
                ('Vch_No', models.CharField(max_length=50, verbose_name='Voucher No')),
                ('Vch_amount', models.FloatField(verbose_name='Voucher Amount')),
                ('MasterCode1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockreport.master1', verbose_name='Master Code')),
            ],
        ),
        migrations.CreateModel(
            name='folio1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D1', models.FloatField(verbose_name='Opening')),
                ('D3', models.FloatField(verbose_name='Opening Stock Value')),
                ('MasterCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockreport.master1', verbose_name='Master Code')),
            ],
        ),
        migrations.CreateModel(
            name='ClosingStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_stock', models.FloatField(default=0, verbose_name='Opening Stock')),
                ('opening_value', models.FloatField(default=0, verbose_name='Opening Value')),
                ('closing_quantity', models.FloatField(default=0, verbose_name='Closing Quantity')),
                ('closing_value', models.FloatField(default=0, verbose_name='Closing Value')),
                ('calculated_date', models.DateTimeField(auto_now_add=True, verbose_name='Calculated Date')),
                ('master_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockreport.master1', verbose_name='Master Item')),
            ],
            options={
                'verbose_name': 'Closing Stock',
                'verbose_name_plural': 'Closing Stocks',
            },
        ),
        migrations.CreateModel(
            name='ClosingBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_balance', models.FloatField(default=0, verbose_name='Opening Balance')),
                ('closing_balance', models.FloatField(default=0, verbose_name='Closing Balance')),
                ('calculated_date', models.DateTimeField(auto_now_add=True, verbose_name='Calculated Date')),
                ('master_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockreport.master1', verbose_name='Master Item')),
            ],
            options={
                'verbose_name': 'Closing Balance',
                'verbose_name_plural': 'Closing Balances',
            },
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'is_active'], name='stockreport_user_id_4cdd56_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['session_key'], name='stockreport_session_c22a77_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['device_id'], name='stockreport_device__227e79_idx'),
        ),
        migrations.AddIndex(
            model_name='tran2',
            index=models.Index(fields=['mastercode1', 'vch_no', 'date'], name='stockreport_masterc_a9d9e1_idx'),
        ),
        migrations.AddIndex(
            model_name='tran2',
            index=models.Index(fields=['RecType'], name='stockreport_RecType_4bb0de_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='closingstock',
            unique_together={('master_item',)},
        ),
        migrations.AlterUniqueTogether(
            name='closingbalance',
            unique_together={('master_item',)},
        ),
    ]
