# Generated by Django 5.2.3 on 2025-06-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockreport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='API endpoint URL')),
                ('username', models.CharField(help_text='API username', max_length=100)),
                ('password', models.CharField(help_text='API password', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Only one configuration can be active at a time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API Configuration',
                'verbose_name_plural': 'API Configurations',
            },
        ),
        migrations.RemoveField(
            model_name='tran2',
            name='voucher_type',
        ),
        migrations.AddField(
            model_name='tran2',
            name='Vch_Type',
            field=models.IntegerField(default=55, verbose_name='Voucher Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='master1',
            name='code',
            field=models.IntegerField(verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='master1',
            name='mastertype',
            field=models.IntegerField(verbose_name='MasterType'),
        ),
        migrations.AlterField(
            model_name='tran2',
            name='vch_no',
            field=models.IntegerField(verbose_name='Voucher No'),
        ),
    ]
