# Generated by Django 4.2 on 2025-08-02 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockreport', '0002_user_api_config_and_sessions'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usersession',
            new_name='stockreport_user_id_4cdd56_idx',
            old_name='stockreport__user_id_8f9c8c_idx',
        ),
        migrations.RenameIndex(
            model_name='usersession',
            new_name='stockreport_session_c22a77_idx',
            old_name='stockreport__session_9c8c8c_idx',
        ),
        migrations.RenameIndex(
            model_name='usersession',
            new_name='stockreport_device__227e79_idx',
            old_name='stockreport__device__8c8c8c_idx',
        ),
    ]
